vimeo/galaxycache

- galaxycache.go
- galaxycache_test.go
- http.go
- http_test.go
- peers.go
Add an error return to the peer Set method in case of failure (primarily for the gRPC implementation, since setting opens the connection immediately and could fail). Also adds Close/Shutdown methods for ending those connections, again primarily for the upcoming gRPC.
> Peer Set Method Error Return and Close/Shutdown for Peer Connections

- galaxycache.go
- galaxycache_test.go
- http.go
- peers.go
Change the Fetch method signature to take strings for galaxy and key instead of protobuf messages, and update the HTTP implementation accordingly.
> Remove protobuf dependency from Fetch method

- galaxycache.go
- observability.go
- Change the tag to specify the Get() call on a galaxy with the galaxy name
- Add the key to all views
> Fix OpenCensus key tags and singleflighted metrics

- http/http.go
- http/http_test.go
- peers.go
Fix path-escaping in HTTP-fetcher and unescape properly so we allow `/`s in both the key and galaxy name. (update tests appropriately to cover all 4 combinations of `/`-presence in keys and galaxies)
Add a `NullFetchProtocol` so tests don't need to depend on the `http` or `grpc` subpackages if they just want to test that the `BackendGetter` implementations work properly (and hence have no peers).
Ensure that HTTP peers have a scheme prefixed with `http://` or `https://` so the same hash-ring can be used for grpc and http peers, thus allowing a seamless migration between the two fetch protocols.
> Match HTTP fetcher capabilities with GRPC improve testing a bit

- grpc/grpcserver.go
- grpc/unsafe_byte_codec.go
Create an `unsafeByteCodec` local to the grpc package that does not copy
the byte-slice in `UnmarshalBinary()`. This should reduce heap
allocations, and may help high-throughput galaxycache gRPC servers with
GC-time.
> gRPC: don't copy bytes before sending on the wire.

- .github/workflows/go.yml
- atomic_int.go
- atomic_int_go1.19.go
- galaxycache.go
- galaxycache_test.go
- go.mod
- go.sum
- hotcache.go
- lru/typed_ll.go
- lru/typed_lru.go
- lru/typed_lru_test.go
- typed_caches.go
- untyped_caches.go
- Bump tested versions to go 1.17+
- Add TypedCache to the `lru` package, and use it in the root-package if go 1.18+
- Move `AtomicInt` into its own file and make it a thin wrapper around `sync/atomic.Int64` when running with go 1.19+
- Pass `valueWithStat` by value since it's rather small anyway. (a few pointers)
> Leverage Generics to improve LRU type-friendliness

- lru/lru.go
- lru/typed_lru.go
The Garbage-Collector enqueues objects to scan to a work-queue in-order.
Place the map before the LRU-stack linked-list so it has an extra
head-start on scanning the much more efficient-to-scan datastructure
(the map).
The GC's mark-phase's traversal of the linked-list is a bit expensive
because it'll have to jump one link at a time, enqueuing the next and/or
previous pointers.  By traversing the map first, a pseudo-random
assortment of entry-points are used, rather than just the first and
last.
If large-ish (where we actually care) the map will be broken up into a
number of pieces for scanning, so the first chunk will be scanned;
enqueuing those linked-list elements before the head and tail get
scanned.
This swap will only have a modest effect because the map is already
scanned, but …
> lru: swap linked-list and map fields

- galaxycache.go
- galaxycache_test.go
- go.mod
- go.sum
- hotcache.go
- peers.go
- promoter/promoter.go
The damping was a bit problematic in that it prevented any hits less
than a second after the initial candidate-cache insertion from having a
non-zero qps calculated.
In this new windowed-QPS type, we specifically avoid including a
time.Time so there are no pointers for the Garbage Collector to scan. As
such, we now measure time relative to a new `baseTime` in the Galaxy. To
facilitate testing, time is now managed by an implementation of the
go-clocks package's Clock interface.
Additionally, this has a few other properties:
- After some time a value is considered "stale" and reset. (so as not
to penalize a key that's hung in the candidate cache for hours
relative to one that's been evicted and brought back)
- QPS is calculated relative to the current "epoch" for that key (which
is either …
> hot/candidate cache: remove damping on key qps 

- .github/workflows/go.yml
- galaxycache_test.go
- lru/lru_test.go
- lru/typed_ll.go
- lru/typed_lru_test.go
A small fix to typed_ll.go fixing invariant adherence in `MoveToFront()`. (three pointer assignments were missed)
This invariant violation would lead the LRU-stack (the linked-list) to get into an invalid state, where the tail pointer is `nil` (and the head pointer is pointing to the incorrect element).
This lead the `Remove()` method to exit early (without doing anything) when the it was evicting the tail element. As a result, `(*cache).removeOldest` in the top-level package would loop indefinitely, as nothing was removed, `bytes()` would return the exact same value every time.
Add some benchmarks because I originally thought this was a performance regression, rather than an infinite loop.
Add some new tests to cover the bug and exercise a number of possible concurrency issues.
It was …
> Fix an invariant violation in the typed Linked List implementation and add testing/benchmarking infrastructure

- .github/workflows/go.yml
gofmt is not aware of build tags and will choke on 1.18+ syntax.  Instead, just focus the format checks on the latest go (1.19).
> Don't Run Format Under Go 1.17

- galaxycache.go
- galaxycache_test.go
- typed_caches.go
- untyped_caches.go
Eliminate an extra lock/unlock on the eviction path by making the
`nbytes` field atomic.
This produces some marginal performance improvements.
e.g. here are the benchmark results from my laptop:
```
[atomic_bytecount] % go test -benchtime 30s -bench . .
goos: linux
goarch: amd64
pkg: github.com/vimeo/galaxycache
cpu: Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
BenchmarkGetsSerialOneKey-4                             19998571              1849 ns/op            1536 B/op         28 allocs/op
BenchmarkGetsSerialManyKeys-4                           10693790              3401 ns/op            2394 B/op         46 allocs/op
BenchmarkGetsParallelManyKeys-4                         12335263              2872 ns/op            2381 B/op         45 allocs/op …
```
> marginal improvement: atomic byte-counts

- .github/workflows/go.yml
- consistenthash/consistenthash.go
- consistenthash/consistenthash_fuzz_test.go
- consistenthash/consistenthash_test.go
When generating the hashring, if there are many segments for an inserted key, there's a nonzero chance of a collision. Previously, the last insert won and we'd end up with an extra copy of that hash-function value in the `keyHashes` slice. Change this so the key that sorts last wins.
Add a fuzz test which I've run for ~10m on my 4-core laptop that make sure that all the internal state is the same for inputs that force collisions.
> consistenthash: resolve hash collisions

- galaxycache.go
- galaxycache_test.go
- go.mod
- go.sum
- peers.go
- peers_test.go
Many possible users of galaxycache are running in environments where it's most convenient to manage peers differently than we allow today.
Most notably, the existing scheme uses the URI for each peer as its ID, and only exposes a `Set()` method on the `Universe` for updating the entire set of peers at once.
This scheme is problematic for two reasons:
1) Many libraries (notably (github.com/vimeo/k8swatcher)[https://github.com/vimeo/k8swatcher]) provide an incremental change-stream, thus forcing the client to aggregate a set of deltas into a current state-set and provide that
2) Mixing the ID in the consistent-hash ring and the URI is limiting. Sometimes it's convenient to change the addressing mode for the peers between versions, and since URIs may include ports, if a user needs to change …
> Incremental peer add & remove

- .github/workflows/go.yml
Apparently we need
[workflow_dispatch](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow) to make this work.
> Allow the Go Workflow to be Triggered Manually

- galaxycache.go
- peers.go
- peers_test.go
Currently there is no way for apps using galaxycache to unit test peers when using AddPeer/RemovePeer methods for incremental changes. ListPeers method returns fetchers map keyed by peer ID can be used to verify the peers and its address by using a RemoteFetcher implementation that provides required information.
> add ListPeers method that returns universe's fetchers.

- .github/workflows/go.yml
- go.mod
- lru/lru.go
- lru/lru_go120.go
With Go 1.20+, interface-types become capable of satisfying comparable
constraints (with a runtime-check/panic). Thus it becomes possible to
deduplicate the two public types in the lru package.
Use build-tags to preserve compatibility with versions below go 1.20 by
preserving the legacy implementation.
> lru: consolidate LRU for go 1.20+ 

- galaxycache.go
- observability.go
Tracks latency for local gets from backend using GetterFunc when there is miss for object in maincache/hotcache.
> latency distribution for local gets per galaxy using GetterFunc

- protocodec/backend_getter_v2.go
- protocodec/backend_getter_v2_test.go
- protocodec/galaxywrap_v2.go
Add a convenience wrapper to make writing BackendGetter implementations
that return a protobuf type a bit more convenient.
This new type has a constructor to take advantage of the much more
powerful function-call-type-parameter inference.
We may add a similar version to the top-level package later, but for
now, type-inference leans in the direction of making it codec-specific.
> protocodec: add BackendGetterV2 and GalaxyGet

- protocodec/backend_getter_v2.go
- protocodec/galaxywrap_v2.go
protocodec.GalaxyGet is particularly hot, and trivial so it should get
inlined. Make a few tweaks to allow inlining. (bringing the cost down
below the magic 80 number in the go compiler)
Similarly, split up protocodec.backendGetterV2.Get to allow inlining of
the fast path. (Amusingly, this also allows the new setSlow to inline,
but that wasn't the goal)
> protocodec: make a few tweaks to allow inlining

- .github/workflows/go.yml
- lru/typed_ll_weak.go
- lru/typed_lru.go
- lru/typed_lru_test.go
- **lru: use weak pointers in LRU stack**
Galaxycache isn't always the most friendly to the Go Garbage Collector.
By keeping a whole pile of pointers in a linked list that the GC needs
to scan in its mark phase, we're compromising the tail latency of any
processes that maintain large numbers of objects in their caches.
Fortunately, Go 1.24 provides weak pointers, so as long as we keep an
"owning" reference in the cache's map, we can make all next/previous
pointers weak pointers and avoid a whole bunch of extra GC work in its
mark phase. (note: this optimization requires that the weak pointers be
at the end of the struct so the GC can skip scanning them if there are
pointers in the value -- if there aren't, then the GC can skip the
linked list entries entirely -- not likely unless one has …
> lru: use weak pointers in LRU stack

- .github/workflows/go.yml
- .gitignore
- galaxycache.go
- galaxycache_test.go
- k8swatch/k8swatch.go
- k8swatch/k8swatch_test.go
- peers.go
- **k8swatch: factor out common switch body**
CreatePod and ModPod events are identical code, but operating on
distinct structs. Pull the body out into an unexported free-function so
we have one code-path to work with.
- **k8swatch: SetIncludeSelf management**
Add a couple methods to the universe to support and add code to k8swatch
that handle updates to the self pod-name.
Due to the slight weirdness of changes that cross modules, we use a
type-assert and progressive enhancement.
After we cut a Galaxycache release with the new methods, we can update
go.mod in the k8swatch submodule.
> k8swatch: factor out body & IncludeSelf Management

- observability.go
A lot of caches have small values (and especially keys). Include a few
small buckets below 1024 so everything isn't always in the smallest
bucket for anything that's not storing massive blobs.
> opencensus views: add small-byte buckets

- .github/workflows/go.yml
- lru/paranoid_check_disabled.go
- lru/paranoid_check_enabled.go
- lru/typed_ll.go
- lru/typed_ll_weak.go
- lru/typed_lru_test.go
- [lru: simplify paranoid GC Linked List testing](https://github.com/vimeo/galaxycache/commit/131a2a5cf6f220ffc7f955609f419c426103afd3)
Move the `paranoidLL` constant to its own build-tagged files so we can
toggle which mode is active by setting a build-tag on the test instead
of having to use sed to modify the constant-value.
- [lru: rewrite FuzzTypedAddRemove](https://github.com/vimeo/galaxycache/commit/d90df581add58d9b7c7dda8509239b08d6d6a430)
Vastly simplify FuzzTypedAddRemove by limiting the keyspace, and make it
more useful by providing triggers for running the GC in parallel.
Use the two high-bits to select the operation and the low-6 bits the
key. (this eliminates the degree of freedom where the fuzzer picks
super-long keys, since it's effectively fuzzing the hash-table's …
> LRU fuzzing overhaul

- consistenthash/chtest/fake_hash.go
- consistenthash/chtest/fake_hash_test.go
- consistenthash/chtest/test_check.go
- **chtest: add key pre-registration (with replicas)**
- **chtest: move in-test check to its own file**
The backwards-compatiblity tests we'll be adding will be much easier to
work with if they can use the chtest package, but since they'll be
separate modules, it'll be useful to have the chtest package.
Since those will be run with `go run` via os/exec, we won't have any
problem setting `-tags`, so we can set a nice, long. scary-sounding
build-tag to gain access to chtest outside a test.
> chtest: key pregistration & non-test build tag

- galaxycache.go
- galaxycachepb/galaxycache.pb.go
- galaxycachepb/galaxycache.proto
- galaxycachepb/galaxycache_grpc.pb.go
- grpc/grpc_test.go
- grpc/grpcclient.go
- grpc/grpcserver.go
- http/http.go
- peers.go
- peers_test.go
- **PeerPicker: add peek picking**
Add a new hashring to the PeerPicker that always excludes "self".
Additionaly, add a method so we can pick the peer that should receive
a specific Peek call.
Make some adjustments to the tests and plumb a clock in through the
universe.
Also, bump go.mod to go 1.23 so we can use chtest in the root package's
tests.
- **GetWithOptions: minimal interface update**
More will come in a later commit, but this provides the minimum required
so we can update the http and grpc subpackages to implement the Peek
method without actually having those methods be called.
- **http: implement Peek method & NotFoundErr handling**
Add support for propagating NotFound errors as
well as adding support for a path that only handles peeks.
Do a bit of minor modernization (e.g. …
> peek: add stub handling in Galaxy & gRPC+HTTP handling

- http/http.go
In order to reuse the connection from HTTP/1.1 requests, we need to have
read the whole body. defer an `io.Copy` into `io.Discard` so even on
errors we can reuse the connection.
> http: consistently drain the response body

- consistenthash/chtest/fake_hash.go
- consistenthash/chtest/fake_hash_test.go
- **chtest: fix segments_per_key calculation**
When writing the initial version of this package, I did a back of the
envelope calculation, and forgot to draw myself a full diagram for the
n=2 and n=3 cases, meaning that I didn't actually _count_ how many
entries I needed with the layout I had. Writing it down and counting
showed that I was off by a factor of 2. (which also jives with the sizes
of the internal maps/slices this package creates (which are
unfortunately only visible in a debugger because they're only propagated
by the hash-function closure's capture)
- **chtest: add block comment explaining hash layout**
Since I needed to write this down on paper to understand the map myself,
I might as well add add a doc-comment that explains it in detail for
everyone. (including future me)
> chtest: fix segments-per-key calculation & add layout explanation

- grpc/grpc_test.go
- grpc/grpcclient.go
- http/http.go
- http/http_test.go
- peers.go
- **peers: prevent self-connection**
Fix a couple places where we forgot to guard against connecting back to
ourselves.
- **http: peek tests & use http.Request directly**
Rewrite the tests considerably to use chtest and make use of iterators.
Most importantly, make sure Peek calls succeed by pre-seeding the
fallthrough instance's cache for some keys.
As part of debugging, I rewrote the URL/prefix handling to actually
work, we might as well commit it all. (it's also more robust without
re-parsing the URL post-string-concatenation)
More importantly, fix some bugs in the path parsing that broke
peek-handling.
- **grpc: NOT_FOUND gRPC status-code support & tests**
Copy the tests from the newly updated http tests to cover peeking and
NOT_FOUND statuses.
> http & grpc peeking & NOT_FOUND fixes + tests

- galaxycache.go
- observability.go
- **observability: add missing views**
After deploying v1.3.0 to a dev cluster, I noticed that we were missing
a view for Peek hits.
For this change, I made a quick pass making sure that all the metrics
defined in observability.go were referenced in `AllViews`.
- **metrics: Peek hits are not cache-hits**
Remove a duplicate increment of MCacheHits that would happen on both the
client and server-side.
MCacheHits with hitlevel=peek would be equivalent to Peek-hits metric,
but need to be filtered out when computing any cache-hitrate (which is
less than useful).
- **GetWithOptions: rewrite doc-comment**
I forgot to update this doc-comment after I changed the contents of
GetOptions to use an enum. Make this a bulleted list that explains
what's happening more clearly.
- **Fix peek metrics**
The …
> Fix peek metrics and reword doc-comment
